spring:
  application:
    name: spring-cloud-gateway
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true     
      routes:
      - id:  api-a
        uri:  lb://INDEX-CODES-SERVICE
        predicates:
          - Path=/api-codes/**
        filters:
          - StripPrefix=1
      - id:  api-b
        uri:  lb://TREND-TRADING-BACKTEST-SERVICE
        predicates:
          - Path=/api-backtest/**
        filters:
          - StripPrefix=1
      - id:  api-c
        uri:  lb://TREND-TRADING-BACKTEST-VIEW
        predicates:
          - Path=/api-view/**
        filters:
          - StripPrefix=1
          
# Eureka Server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug